"""Add first_name and last_name to users

Revision ID: 55cbb9a2e5fa
Revises: af25c90772cc
Create Date: 2026-02-03 10:02:30.278150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cbb9a2e5fa'
down_revision = 'af25c90772cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.alter_column('covered_member_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.alter_column('covered_member_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
